Repository siv2r/kidney-exchange, pull requests merged in 2021-05, with the labels that each got.

#129 Project setup video in read me
  README.md
Labels: Level3, gssoc21

#130 Deleted the ISSUE_TEMPLATE.md directory
  .github/ISSUE_TEMPLATE.md/bug_report.md
  .github/ISSUE_TEMPLATE.md/feature_request.md
Labels: Level2, gssoc21

#139 Updating pull request template(issue no. 124)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Level3, gssoc21

#143 added required links in some files
  pages/dataOverview.php
  pages/reg-form.php
  pages/register_hospital.php
Labels: Level3, gssoc21

#147 Enhancement required in Sign Up
  pages/signup.php
Labels: Level3, gssoc21

#144 login enhancement
  pages/login.php
Labels: Level3, gssoc21

#149 added welcome bot
  .github/workflows/config.yml
Labels: Level3, gssoc21

#153 added auto assign bot
  .github/workflows/Issue-assign.yml
Labels: Level3, gssoc21

#148 made proper documentation
  README.md
  docs/CONTRIBUTING.md
  docs/CreatePR.md
  images/logo3.png
  include/kidney_chain.png
Labels: Level2, gssoc21

#156 Width bug in Overview page Fixed
  css/table-style.css
  pages/dataOverview.php
Labels: gssoc21

#161 removed all comments having large size
  pages/form-process.php
  templates/d_hla.php
  templates/edit_dHla.php
  templates/edit_rHla.php
  templates/r_hla.php
Labels: Level3, gssoc21

#163 fix
  .github/config.yml
Labels: Level2, gssoc21

#157 added new_contributors_readme
  README.md
  docs/newContributors.md
Labels: Level3, gssoc21

#160 fixed data overview responsiveness
  pages/dataOverview.php
Labels: Level3, gssoc21

#169 removed a comment from json.func.php
  functions/json.func.php
Labels: Level3, gssoc21

#168 Responsiveness of REGISTRATION FORM Page i.e (reg-form.php)
  css/form-style.css
  pages/reg-form.php
Labels: Level3, gssoc21

#175 Overview section on home page
  index.php
Labels: Level3, gssoc21

#178 added footer
  include/footer.inc.php
Labels: Level3, gssoc21

#179 added a customizable message to issue assign bot
  .github/workflows/Issue-assign.yml
Labels: Level3, gssoc21

#198 Added Project Board to track features
  README.md
Labels: Level3, gssoc21

#196 made project setup documentation
  build.md
Labels: Level3, gssoc21

#187 added the sweet alert before logout
  templates/navBar.php
Labels: Level3, gssoc21

#185 Improving Responsiveness of register_hospital.php
  pages/register_hospital.php
Labels: Level3, gssoc21

#180 Sweet alert for Delete, Status, Edit in the dataoverview.php
  pages/dataOverview.php
  pages/editPairForm.php
Labels: Level3, gssoc21

#182 Fixed the bug and included the footer
  pages/dataOverview.php
Labels: Level3, gssoc21

#189 fixed the issue with footer
  pages/pairwiseMatch.php
Labels: Level3, gssoc21

#191 fixed the issue with footer
  pages/globalMatch.php
Labels: Level3, gssoc21

#193 fixed the issue with footer
  pages/dataSearch.php
Labels: Level3, gssoc21

#195 fixed the footer in displayGlobalMatch.php
  pages/displayGlobalMatch.php
Labels: Level3, gssoc21

#201 removed logo from navbar and footer
  README.md
  images/logo3.png
  include/footer.inc.php
  templates/navBar.php
Labels: Level3, gssoc21

#203 enhancement in footer
  include/footer.inc.php
Labels: Level3, gssoc21

#206 fixed the navbar padding
  templates/navBar.php
Labels: Level3, gssoc21

#209 fixed responsiveness in global match.php
  pages/globalMatch.php
Labels: Level3, gssoc21

#207 fixed responsiveness of pairwise page on small screen
  pages/pairwiseMatch.php
Labels: Level3, gssoc21

#211 fixed the responsiveness of dataSummary
  pages/dataSummary.php
Labels: Level3, gssoc21

#215 name of user Instead of just logout
  templates/navBar.php
Labels: Level3, gssoc21

#213 fixed the responsiveness for edit pair page
  css/form-style.css
  pages/editPairForm.php
Labels: Level3, gssoc21

#216 Added docstrings for the functions
  global_match/precomputation.py
Labels: Level3, gssoc21

#223 Responsivesness of displayPairwiseMatch.php fixed
  pages/displayPairwiseMatch.php
Labels: Level3, gssoc21

#220 Added docstrings for hovering.py file
  global_match/hovering.py
Labels: Level3, gssoc21

#221 Added docstrings for solution.py file
  global_match/solution.py
Labels: Level3, gssoc21

#219 Added docstrings for jsonConversion.py file
  global_match/jsonConversion.py
Labels: Level3, gssoc21

#218 Added docstrings for pipeline.py file
  global_match/pipeline.py
Labels: Level3, gssoc21

#217 Added docstrings for kidney_exchange.py file
  global_match/kidney_exchange.py
Labels: Level3, gssoc21

#229 removed red color from hover
  templates/navBar.php
Labels: Level3, gssoc21

#225 removed footer completely
  include/footer.inc.php
Labels: Level3, gssoc21

#227 removed overview section completely
  index.php
Labels: Level3, gssoc21

#231 fixed the bug
  pages/pairData.php
Labels: Level3, gssoc21

#238 php file updated
  functions/scoring.func.php
Labels: Level3, gssoc21

#239 Updated reg-form.js file
  js/reg-form.js
Labels: Level3, gssoc21

#244 added a back to top in reg-form.php
  pages/reg-form.php
Labels: Level3, gssoc21

#242 added code to handle 404 error
  .htaccess
  pages/404.php
Labels: Level3, gssoc21

#260 fixed grammatical error
  docs/newContributors.md
Labels: Level3, gssoc21

#264 fixed a bug in message.php
  pages/message.php
Labels: Level3, gssoc21

#262 fixed a error
  docs/newContributors.md
Labels: Level3, gssoc21

#261 fixed counting mistake
  docs/newContributors.md
Labels: Level3, gssoc21

#253 Updated validateHosp.js
  js/validateHosp.js
Labels: Level3, gssoc21

#248 Included new discord server link
  README.md
Labels: Level3, gssoc21

#250 Updated scoring.func.php file
  functions/scoring.func.php
Labels: Level3, gssoc21

#269 moved all css and js to seperate file
  css/backToTop.css
  js/backToTop.js
  pages/reg-form.php
Labels: Level3, gssoc21
