Repository siv2r/kidney-exchange, pull requests merged in 2021-03, with the labels that each got.

#62 Solved Form Validation Issue #29
  js/editPairForm.js
  js/reg-form.js
Labels: gssoc21, level2

#75 Update README.md
  README.md
Labels: gssoc21, level0

#74 Solved spelling mistake of status issue #70
  pages/reg-form.php
Labels: gssoc21, level2

#76 Added Contributor
  README.md
Labels: gssoc21, level2

#77 Added Techstack
  README.md
Labels: gssoc21, level2

#73 Solved Improving Home Page Issue #63
  index.php
Labels: gssoc21, level2

#85 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Level2, gssoc21

#92 Better documentation #26
  README.md
  images/kidney_chain.png
Labels: Level0, gssoc21
