Repository siv2r/kidney-exchange, pull requests merged in 2021-04, with the labels that each got.

#103 Fixed Issue#94 "Added Brand Logo on Navbar"
  README.md
  images/logo3.png
  templates/navBar.php
Labels: Level3, gssoc21

#106 Solved Remove Brand Logo Issue #105
  README.md
Labels: Level0, gssoc21

#108 Issue 26
  README.md
Labels: Level0, gssoc21

#102 [Gssoc'21] Added the show password feature
  js/showpassword.js
  pages/login.php
  pages/signup.php
Labels: Level3, gssoc21

#80 Solved issue #69 Limit Age Input
  pages/reg-form.php
Labels: Level3, gssoc21

#111 Issue #109 - Adjust Show password font size
  pages/login.php
  pages/signup.php
Labels: Level2, gssoc21

#114 Login Responsiveness Fixed
  pages/login.php
Labels: Level3, gssoc21

#116 Fixed Responsiveness of Register page
  pages/signup.php
Labels: Level3, gssoc21

#118 home page is responsive now
  index.php
Labels: Level3, gssoc21
