Repository siv2r/kidney-exchange, pull requests merged in 2021-06, with the labels that each got.

#247 added back to top button in register_hospital.php
  css/form-style.css
  pages/register_hospital.php
Labels: Level3, gssoc21

#275 updated contributors.md file
  docs/newContributors.md
Labels: Level3, gssoc21

#252 Updated php file
  functions/scoring.func.php
Labels: Level3, gssoc21

#266 added back to top in dataSummary.php
  pages/dataSummary.php
Labels: Level3, gssoc21

#267 added html and bootstrap in tech statck
  README.md
Labels: Level3, gssoc21

#272 fixed the background to cover 100% height in datasearch page
  pages/dataSearch.php
Labels: Level3, gssoc21

#249 Upadated showpassword.js
  js/showpassword.js
Labels: Level0, gssoc21

#274 Added 404 page template
  css/404.css
  pages/404.php
Labels: Level3, gssoc21

#280 Feature-added
  docs/newContributors.md
  images/kidney.png
  index.php
  pages/login.php
  pages/signup.php
  templates/db-connect.php
Labels: LGMSOC21, Level4

#293 Update Issue-assign.yml
  .github/workflows/Issue-assign.yml
Labels: LGMSOC21, Level3

#287 Extra Comments deleted
  images/avatar.jpg
  images/kidney_chain.png
  images/red-avatar.png
  images/user.png
  include/functions.inc.php
  include/kidney_chain.png
Labels: LGMSOC21, Level3

#294 added hospital table
  css/404.css
  pages/404.php
  pages/displayGlobalMatch.php
  pages/displayRegHosp.php
  templates/navBar.php
Labels: LGMSOC21, Level4

#295 fixed the radio button issue
  js/reg-form.js
Labels: LGMSOC21, Level3

#301 code of conduct
  CODE_OF_CONDUCT.md
Labels: LGMSOC21, Level2

#300 Added Contribution Guidelines
  README.md
Labels: LGMSOC21, Level1

#309 faq
  docs/FAQ.md
Labels: LGMSOC21, Level3

#302 fix responsive nature
  pages/dataSummary.php
  pages/jsonData.php
  pages/reg-form.php
  templates/navBar.php
Labels: LGMSOC21, Level4

#315 auto-formatter
  .github/workflows/autoblack.yml
  .github/workflows/format_code.yml
Labels: LGMSOC21, Level3

#319 added more badges with links
  README.md
Labels: LGMSOC21, Level2

#318 fixes credential issue
  .github/workflows/format_code.yml
  .gitignore
  composer.json
  db-connect.php
  generate_json/cmpGraph.php
  generate_json/jsonDump.php
  global_match/findGlobalMatch.php
  include/addAdmin.php
  include/deleteData.inc.php
  include/findPairwiseMatch.inc.php
  include/getHosp.inc.php
  include/getPairData.inc.php
  include/login.inc.php
  include/signup.inc.php
  include/toggleStatus.inc.php
  include/updatePair.inc.php
  pages/dataOverview.php
  pages/dataSummary.php
  pages/displayRegHosp.php
  pages/editPairForm.php
  pages/form-process.php
  pages/pairData.php
  pages/reg-form.php
Labels: LGMSOC21, Level4

#323 removed the startCapital validation
  js/editPairForm.js
  js/reg-form.js
  js/validateHosp.js
Labels: LGMSOC21, Level2

#322 Modified the CSS of the login and signup page.
  pages/login.php
  pages/signup.php
Labels: LGMSOC21, Level4

#327 added eye icon
  js/showpassword.js
  pages/login.php
  pages/signup.php
Labels: LGMSOC21, Level3
